export type ClauseKind = 'REFUNDABLE_REQUIRED' | 'MAX_TOTAL_PRICE_USD' | 'MIN_CANCELLATION_HOURS' | 'LATEST_CHECKIN_UNIX';
export type Clause = { kind: ClauseKind; value: boolean | number };
export type Edge = {
  edge_index: number;
  parent: string;
  child: string;
  mandate_text: string;
  accepted: boolean;
  recorded_at_unix: number;
  accepted_at_unix: number;
  acceptance_deadline_unix: number;
  uses_prime_bond: boolean;
  bond_locked: string;
};
export type ClauseResult = { clause_index: number; responsible_edge: number; liability: string; carries: boolean[] };
export type CaseState = {
  case_id: string;
  case_ref: string;
  principal: string;
  prime_agent: string;
  receipt_authority: string;
  status: string;
  clauses: Clause[];
  bond_per_clause_wei: string;
  required_bond_wei: string;
  prime_bond_locked: string;
  prime_accepted: boolean;
  current_executor: string;
  edges: Edge[];
  pending_edge_index: number;
  receipt: Record<string, unknown>;
  breached_clause_indexes: number[];
  evaluations: Record<string, 'CARRIES' | 'DOES_NOT_CARRY'>;
  evaluation_count: number;
  required_evaluations: number;
  settlement: { type?: string; principal_compensation_wei?: string; clause_results?: ClauseResult[] };
  execution_deadline_unix: number;
  evaluation_deadline_unix: number;
  updated_at_unix: number;
};
